### ISSUE TITLE
odoo 13社区、企业版无法钉钉扫描成功登陆

### ISSUE THREAD

**Issue by erikguo** [suxuefeng20/odooDinDin#166]
我们检查发现，是在员工模块中调用“创建系统用户”功能时，虽然成功建立了系统用户，但是 ding_user_id 和 ding_user_phone没用正确写入res_users数据表（这两个字段都是空）导致的问题，但是，看了你写的代码下来，感觉都是正确的，麻烦你可以帮忙查一下是什么原因吗？谢谢

@suxuefeng20

**Comment by cd-feng** [comment]
好的，近期我检查一下

**Comment by erikguo** [comment]
成功了， 谢谢  @suxuefeng20
