### ISSUE TITLE
员工性别未同步

### ISSUE THREAD

**Issue by leangjia** [suxuefeng20/odooDinDin#92]
钉钉同步后在odoo里所有员工都是男性未婚，女同胞有意见的。

**Comment by leangjia** [comment]
@ @suxuefeng20

**Comment by niulinlnc** [comment]
钉钉通讯录同步sdk没有提供性别，在钉钉智能人事sdk有性别，可以考虑从智能人事同步花名册的时候，把odoo里员工的性别同步了。 @suxuefeng20

**Comment by cd-feng** [comment]
可以的，有空再加上去就好了@niulinlnc

**Comment by cd-feng** [comment]
已通过花名册更正
